# config/settings.py
NIFTY_100_UNIVERSAL_BASKET = [
    "RELIANCE.NS", "TCS.NS", "HDFCBANK.NS", "INFY.NS", "ICICIBANK.NS",
    "SBIN.NS", "BHARTIARTL.NS", "LICI.NS", "KOTAKBANK.NS", "ITC.NS",
    "HINDUNILVR.NS", "LT.NS", "BAJFINANCE.NS", "HCLTECH.NS", "MARUTI.NS",
    "SUNPHARMA.NS", "AXISBANK.NS", "TITAN.NS", "ULTRACEMCO.NS", "TATAMOTORS.NS"
]
DATA_CACHE_DIR = "data_cache"
INITIAL_CAPITAL = 500000
DEFAULT_RISK_PER_TRADE = 0.01
BENCHMARK_TICKER = "^NSEI"
